SELECT
    A.AUTHOR_ID, 
    A.AUTHOR_NAME,
    BS.CATEGORY,
    SUM(BS.SALES * BS.PRICE) AS TOTAL_SALES
FROM 
    (
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, S.SALES
    FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01-%'
    ) BS
    JOIN AUTHOR A ON A.AUTHOR_ID = BS.AUTHOR_ID
GROUP BY
    A.AUTHOR_ID, BS.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC, BS.CATEGORY DESC;
    