SELECT
    F.CATEGORY,
    F.PRICE AS MAX_PRICE,
    F.PRODUCT_NAME
FROM
    FOOD_PRODUCT F JOIN (
    SELECT 
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM 
        FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY 
        CATEGORY
    ) P
    ON F.CATEGORY = P.CATEGORY AND MAX_PRICE = F.PRICE
GROUP BY 
    F.CATEGORY
ORDER BY 
    MAX_PRICE DESC;